# -*- coding: utf-8 -*-
"""Proyecto2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9TgIr3fqVPFxFvcpCkxwTIdLisAHEK6
"""

# Usuario de ejemplo
user = ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]]

# Paso 1: limpiar el nombre (quitar espacios y reemplazar _ por espacio)
user[1] = user[1].strip().replace('_', ' ')

# Paso 2: dividir el nombre en una lista
user[1] = user[1].split()

# Paso 3: convertir la edad a entero
user[2] = int(user[2])


# Mostrar resultado
print(user)

# Lista original de categorías favoritas escritas en mayúsculas
fav_categories = ['ELECTRONICS', 'SPORT', 'BOOKS']

# 1. Lista vacía donde almacenaremos las categorías convertidas a minúsculas
fav_categories_low = []

# 2. Recorremos cada categoría en la lista original
for category in fav_categories:
    # 2. Convertimos la categoría a minúscula utilizando el método lower()
    lowered_category = category.lower()

    # 3. Agregamos la categoría convertida a la nueva lista
    fav_categories_low.append(lowered_category)

# 4. Mostramos en pantalla la lista resultante con las categorías en minúsculas
print(fav_categories_low)

def clean_user(user):
    # Limpia y divide el nombre
    name = user[1].strip().replace('_', ' ').split()

    # Edad como entero
    age = int(user[2])

    # Categorías a minúsculas
    categories = []
    for cat in user[3]:
        categories.append(cat.lower())

    return [user[0], name, age, categories, user[4]]

# Prueba
test_user = ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]]
print(clean_user(test_user))

users_raw = [
    ['32415', ' mike_reed ', 32.0, ['ELECTRONICS', 'SPORT', 'BOOKS'], [894, 213, 173]],
    ['31980', 'kate morgan', 24.0, ['CLOTHES', 'BOOKS'], [439, 390]],
    ['32156', ' john doe ', 37.0, ['ELECTRONICS', 'HOME', 'FOOD'], [459, 120, 99]],
    ['32761', 'SAMANTHA SMITH', 29.0, ['CLOTHES', 'ELECTRONICS', 'BEAUTY'], [299, 679, 85]],
    ['32984', 'David White', 41.0, ['BOOKS', 'HOME', 'SPORT'], [234, 329, 243]],
    ['33001', 'emily brown', 26.0, ['BEAUTY', 'HOME', 'FOOD'], [213, 659, 79]],
    ['33767', ' Maria Garcia', 33.0, ['CLOTHES', 'FOOD', 'BEAUTY'], [499, 189, 63]],
    ['33912', 'JOSE MARTINEZ', 22.0, ['SPORT', 'ELECTRONICS', 'HOME'], [259, 549, 109]],
    ['34009', 'lisa wilson ', 35.0, ['HOME', 'BOOKS', 'CLOTHES'], [329, 189, 329]],
    ['34278', 'James Lee', 28.0, ['BEAUTY', 'CLOTHES', 'ELECTRONICS'], [189, 299, 579]]
]

users_clean = []

for user in users_raw:
    users_clean.append(clean_user(user))

print(users_clean)

users_clean = [['32415', ['mike', 'reed'], 32, ['electronics', 'sport', 'books'], [894, 213, 173]],
         			 ['31980', ['kate', 'morgan'], 24, ['clothes', 'books'], [439, 390]],
         			 ['32156', ['john', 'doe'], 37, ['electronics', 'home', 'food'], [459, 120, 99]],
         			 ['32761', ['samantha', 'smith'], 29, ['clothes', 'electronics', 'beauty'], [299, 679, 85]],
         			 ['32984', ['david', 'white'], 41, ['books', 'home', 'sport'], [234, 329, 243]],
         			 ['33001', ['emily', 'brown'], 26, ['beauty', 'home', 'food'], [213, 659, 79]],
         			 ['33767', ['maria', 'garcia'], 33, ['clothes', 'food', 'beauty'], [499, 189, 63]],
         			 ['33912', ['jose', 'martinez'], 22, ['sport', 'electronics', 'home'], [259, 549, 109]],
         			 ['34009', ['lisa', 'wilson'], 35, ['home', 'books', 'clothes'], [329, 189, 329]],
         			 ['34278', ['james', 'lee'], 28, ['beauty', 'clothes', 'electronics'], [189, 299, 579]]]

revenue = 0

for user in users_clean:
    revenue += sum(user[4])

print(revenue)

users_clean = [['32415', ['mike', 'reed'], 32, ['electronics', 'sport', 'books'], [894, 213, 173]],
         			 ['31980', ['kate', 'morgan'], 24, ['clothes', 'books'], [439, 390]],
         			 ['32156', ['john', 'doe'], 37, ['electronics', 'home', 'food'], [459, 120, 99]],
         			 ['32761', ['samantha', 'smith'], 29, ['clothes', 'electronics', 'beauty'], [299, 679, 85]],
         			 ['32984', ['david', 'white'], 41, ['books', 'home', 'sport'], [234, 329, 243]],
         			 ['33001', ['emily', 'brown'], 26, ['beauty', 'home', 'food'], [213, 659, 79]],
         			 ['33767', ['maria', 'garcia'], 33, ['clothes', 'food', 'beauty'], [499, 189, 63]],
         			 ['33912', ['jose', 'martinez'], 22, ['sport', 'electronics', 'home'], [259, 549, 109]],
         			 ['34009', ['lisa', 'wilson'], 35, ['home', 'books', 'clothes'], [329, 189, 329]],
         			 ['34278', ['james', 'lee'], 28, ['beauty', 'clothes', 'electronics'], [189, 299, 579]]]


for user in users_clean:
        if user[2] < 30:
            print(user[1][0])

users_clean = [['32415', ['mike', 'reed'], 32, ['electronics', 'sport', 'books'], [894, 213, 173]],
         			 ['31980', ['kate', 'morgan'], 24, ['clothes', 'books'], [439, 390]],
         			 ['32156', ['john', 'doe'], 37, ['electronics', 'home', 'food'], [459, 120, 99]],
         			 ['32761', ['samantha', 'smith'], 29, ['clothes', 'electronics', 'beauty'], [299, 679, 85]],
         			 ['32984', ['david', 'white'], 41, ['books', 'home', 'sport'], [234, 329, 243]],
         			 ['33001', ['emily', 'brown'], 26, ['beauty', 'home', 'food'], [213, 659, 79]],
         			 ['33767', ['maria', 'garcia'], 33, ['clothes', 'food', 'beauty'], [499, 189, 63]],
         			 ['33912', ['jose', 'martinez'], 22, ['sport', 'electronics', 'home'], [259, 549, 109]],
         			 ['34009', ['lisa', 'wilson'], 35, ['home', 'books', 'clothes'], [329, 189, 329]],
         			 ['34278', ['james', 'lee'], 28, ['beauty', 'clothes', 'electronics'], [189, 299, 579]]]


for user in users_clean:
    total_spent = sum(user[4])

    if user[2] < 30 and total_spent > 1000:
        print(user[1][0])

users_clean = [['32415', ['mike', 'reed'], 32, ['electronics', 'sport', 'books'], [894, 213, 173]],
         			 ['31980', ['kate', 'morgan'], 24, ['clothes', 'books'], [439, 390]],
         			 ['32156', ['john', 'doe'], 37, ['electronics', 'home', 'food'], [459, 120, 99]],
         			 ['32761', ['samantha', 'smith'], 29, ['clothes', 'electronics', 'beauty'], [299, 679, 85]],
         			 ['32984', ['david', 'white'], 41, ['books', 'home', 'sport'], [234, 329, 243]],
         			 ['33001', ['emily', 'brown'], 26, ['beauty', 'home', 'food'], [213, 659, 79]],
         			 ['33767', ['maria', 'garcia'], 33, ['clothes', 'food', 'beauty'], [499, 189, 63]],
         			 ['33912', ['jose', 'martinez'], 22, ['sport', 'electronics', 'home'], [259, 549, 109]],
         			 ['34009', ['lisa', 'wilson'], 35, ['home', 'books', 'clothes'], [329, 189, 329]],
         			 ['34278', ['james', 'lee'], 28, ['beauty', 'clothes', 'electronics'], [189, 299, 579]]]

for user in users_clean:
    if "clothes" in user[3]:
        print(user[1][0], user[2])

users_clean = [['32415', ['mike', 'reed'], 32, ['electronics', 'sport', 'books'], [894, 213, 173]],
         			 ['31980', ['kate', 'morgan'], 24, ['clothes', 'books'], [439, 390]],
         			 ['32156', ['john', 'doe'], 37, ['electronics', 'home', 'food'], [459, 120, 99]],
         			 ['32761', ['samantha', 'smith'], 29, ['clothes', 'electronics', 'beauty'], [299, 679, 85]],
         			 ['32984', ['david', 'white'], 41, ['books', 'home', 'sport'], [234, 329, 243]],
         			 ['33001', ['emily', 'brown'], 26, ['beauty', 'home', 'food'], [213, 659, 79]],
         			 ['33767', ['maria', 'garcia'], 33, ['clothes', 'food', 'beauty'], [499, 189, 63]],
         			 ['33912', ['jose', 'martinez'], 22, ['sport', 'electronics', 'home'], [259, 549, 109]],
         			 ['34009', ['lisa', 'wilson'], 35, ['home', 'books', 'clothes'], [329, 189, 329]],
         			 ['34278', ['james', 'lee'], 28, ['beauty', 'clothes', 'electronics'], [189, 299, 579]]]

def get_clients_by_category(users, category):
    result = []

    for user in users:
        if category in user[3]:
            total_spent = sum(user[4])
            full_name = user[1][0] + " " + user[1][1]
            result.append([user[0], full_name, user[2], total_spent])

    return result

# Prueba con la categoría 'home'
filtered = get_clients_by_category(users_clean, 'home')
print(filtered)